
#define CUSTOM_ITEM_LIST \
    QGHELMET(phase2_Alpha), \
    QGHELMET(phase2_Apathy), \
    QGHELMET(phase2_Bean), \
    QGHELMET(phase2_Bigfella), \
    QGHELMET(phase2_Blue), \
    QGHELMET(phase2_CJ), \
    QGHELMET(phase2_Crometheus), \
    QGHELMET(phase2_Dutchmann), \
    QGHELMET(phase2_Fallen), \
    QGHELMET(phase2_Ghoul), \
    QGHELMET(phase2_Grandpa), \
    QGHELMET(phase2_Hippo), \
    QGHELMET(phase2_Husky), \
    QGHELMET(phase2_Impulse), \
    QGHELMET(phase2_Juicy), \
    QGHELMET(phase2_Kalo), \
    QGHELMET(phase2_Kona), \
    QGHELMET(phase2_Lone), \
    QGHELMET(phase2_Orion), \
    QGHELMET(phase2_Paddy), \
    QGHELMET(phase2_Queue), \
    QGHELMET(phase2_Quake), \
    QGHELMET(phase2_Roach), \
    QGHELMET(phase2_Rodi), \
    QGHELMET(phase2_Ryan), \
    QGHELMET(phase2_Sasquatch), \
    QGHELMET(phase2_Shadow), \
    QGHELMET(phase2_Sleepy), \
    QGHELMET(phase2_Spiritual), \
    QGHELMET(phase2_Swift), \
    QGHELMET(phase2_Topdog), \
    QGHELMET(phase2_Turq), \
    QGHELMET(phase2_Odin), \
    QGHELMET(phase2_Ricebowl), \
    QGHELMET(arc_Blue), \
    QGHELMET(arc_Nook), \
    QGHELMET(arc_Boxing), \
    QGHELMET(arc_Husky), \
    QGHELMET(arc_Firehawk), \
    QGHELMET(arc_Graves), \
    QGHELMET(arf_Drom), \
    QGHELMET(arf_Spec), \
    QGHELMET(arf_Subbie), \
    QGHELMET(barc_CJ), \
    QGHELMET(barc_Firehawk), \
    QGHELMET(barc_Gus), \
    QGHELMET(engineer_Hippo), \
    QGHELMET(engineer_Lone), \
    QGHELMET(engineer_Paddy), \
    QGHELMET(engineer_Shark), \
    QGHELMET(pilot_Bandit), \
    QGHELMET(pilot_Killa), \
    QGHELMET(pilot_Kurt), \
    QGHELMET(pilot_Lego), \
    QGHELMET(pilot_Odin), \
    QGHELMET(pilot_Pigs), \
    QGHELMET(pilot_Sleepy), \
    QGHELMET(pilot_Trash), \
    QGHELMET(tanker_Dutchmann), \
    QGHELMET(tanker_Gambler), \
    QGHELMET(tanker_Lone), \
    QGHELMET(tanker_Maverick) \

#define STANDARD_ITEM_LIST \
    QGHELMET(phase2_CR), \
    QGHELMET(phase2_CT), \
    QGHELMET(phase2_SCT), \
    QGHELMET(phase2_VCT), \
    QGHELMET(phase2_CLC), \
    QGHELMET(phase2_CSP1), \
    QGHELMET(ARC), \
    QGHELMET(arc_Trainee), \
    QGHELMET(arc_Veteran), \
    QGHELMET(ARF), \
    QGHELMET(arf_Billeted), \
    QGHELMET(BARC), \
    QGHELMET(barc_Billet), \
    QGHELMET(engineer_Billet), \
    QGHELMET(Pilot_Billeted), \
    QGHELMET(Tanker_Billeted), \
    QGHELMET(Airborne_billeted), \
    QGHELMET(phase1_CT), \
    QGHELMET(phase1_SCT), \
    QGHELMET(phase1_VCT), \
    QGHELMET(phase1_CLC), \
    QGHELMET(phase1_CSP1), \
    QGHELMET(phase1_ARC), \
    QGHELMET(phase1_AlphaARC), \
    QGHELMET(phase1_NCO), \
    QGHELMET(phase1_Command) \

#define UNIT_LIST \
