/*class CfgPatches
{
	class SW13IB_CIS_Mercenary
	{
		name="SW13IB_CIS_Mercenary";
		author="WPEC Dev";
		requiredAddons[]={};
		weapons[]={};
		units[]=
		{
			"SW13IB_CIS_MercTrooper_Unit",
			"SW13IB_CIS_MercHeavy_Unit",
			"SW13IB_CIS_MercNCO_Unit",
			"SW13IB_CIS_MercSniper_Unit",
			"SW13IB_CIS_MercMedic_Unit"
		};
	};
};
class CfgEditorSubcategories
{
	class SW13IB_CIS_Mercenary
	{
		displayName="[CIS] Mercenary Division";
	};
};
class CfgVehicles
{
	class 3AS_U_CIS_Light;
	class SW13IB_CIS_MercTrooper_Unit: 3AS_U_CIS_Light
	{
		scope=2;
		scopeCurator=2;
		displayName="CIS Mercenary";
		editorSubcategory="SW13IB_CIS_Mercenary";
		side=0;
		faction="SW13IB_CIS";
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		LinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Weapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Magazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		minTotalDamageThreshold=0.001;
		impactDamageMultiplier=0.5;
	};
	class 3AS_U_CIS_Heavy;
	class SW13IB_CIS_MercHeavy_Unit: 3AS_U_CIS_Heavy
	{
		scope=2;
		scopeCurator=2;
		displayName="CIS Heavy Mercenary";
		editorSubcategory="SW13IB_CIS_Mercenary";
		side=0;
		faction="SW13IB_CIS";
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		LinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Weapons[]=
		{
			"SW13IB_INDFOR_M247",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SW13IB_INDFOR_M247",
			"Throw",
			"Put"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Magazines[]=
		{
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SW13IB_Human_M247_Auto_mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		minTotalDamageThreshold=0.001;
		impactDamageMultiplier=0.5;
	};
	class 3AS_U_CIS_Officer;
	class SW13IB_CIS_MercNCO_Unit: 3AS_U_CIS_Officer
	{
		scope=2;
		scopeCurator=2;
		displayName="CIS Mercenary Officer";
		editorSubcategory="SW13IB_CIS_Mercenary";
		side=0;
		faction="SW13IB_CIS";
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		LinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_Helmet_wht",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Weapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_Helmet_wht",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Magazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		minTotalDamageThreshold=0.001;
		impactDamageMultiplier=0.5;
	};
	class 3AS_U_CIS_Medic;
	class SW13IB_CIS_MercMedic_Unit: 3AS_U_CIS_Medic
	{
		scope=2;
		scopeCurator=2;
		displayName="CIS Mercenary Medic";
		editorSubcategory="SW13IB_CIS_Mercenary";
		side=0;
		faction="SW13IB_CIS";
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		LinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_Helmet_med",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Weapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SW13IB_INDFOR_BR55",
			"Throw",
			"Put"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_Helmet_med",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Magazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SW13IB_Human_BR55_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		minTotalDamageThreshold=0.001;
		impactDamageMultiplier=0.5;
	};
	class SW13IB_CIS_MercSniper_Unit: 3AS_U_CIS_Light
	{
		scope=2;
		scopeCurator=2;
		displayName="CIS Sniper Mercenary";
		editorSubcategory="SW13IB_CIS_Mercenary";
		side=0;
		faction="SW13IB_CIS";
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		LinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Weapons[]=
		{
			"SW13IB_INDFOR_SRS99C",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SW13IB_INDFOR_SRS99C",
			"Throw",
			"Put"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"SW13IB_NVG_chip",
			"OPTRE_UNSC_VX16_HelmetV",
			"JLTS_droid_comlink",
			"ItemCompass",
			"ItemWatch"
		};
		Magazines[]=
		{
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SW13IB_Human_SRS_Sniper_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		minTotalDamageThreshold=0.001;
		impactDamageMultiplier=0.5;
	};
};
class cfgMods
{
	author="ChaosViking";
	timepacked="1677279925";
};*/
